In [1]:
import pandas as pd
df=pd.read_csv("heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [2]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [9]:
from scipy.stats import zscore

cols = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']

z_scores = df[cols].apply(zscore)

df_no_outliers = df[(z_scores.abs() <= 3).all(axis=1)]

df_no_outliers.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Z_Score
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.825070
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,-0.171961
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,0.770188
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.139040
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,-0.034755

In [13]:
df=df_no_outliers
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Z_Score
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0,0.825070
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1,-0.171961
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0,0.770188
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1,0.139040
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0,-0.034755

In [15]:
dummies = pd.get_dummies(
    df[['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']]
)

merged = pd.concat([df, dummies], axis=1)

merged.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,M,ATA,140,289,0,Normal,172,N,0.0,...,False,False,False,True,False,True,False,False,False,True
1,49,F,NAP,160,180,0,Normal,156,N,1.0,...,True,False,False,True,False,True,False,False,True,False
2,37,M,ATA,130,283,0,ST,98,N,0.0,...,False,False,False,False,True,True,False,False,False,True
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,...,False,False,False,True,False,False,True,False,True,False
4,54,M,NAP,150,195,0,Normal,122,N,0.0,...,True,False,False,True,False,True,False,False,False,True

In [16]:
final_df = merged.drop(
    ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope'],
    axis=1
)

final_df.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Z_Score,Sex_F,Sex_M,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,0.825070,False,True,...,False,False,False,True,False,True,False,False,False,True
1,49,160,180,0,156,1.0,1,-0.171961,True,False,...,True,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,0,0.770188,False,True,...,False,False,False,False,True,True,False,False,False,True
3,48,138,214,0,108,1.5,1,0.139040,True,False,...,False,False,False,True,False,False,True,False,True,False
4,54,150,195,0,122,0.0,0,-0.034755,False,True,...,True,False,False,True,False,True,False,False,False,True

In [25]:
x=final_df.drop(['HeartDisease'],axis=1)
x.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Z_Score,Sex_F,Sex_M,ChestPainType_ASY,...,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0.825070,False,True,False,...,False,False,False,True,False,True,False,False,False,True
1,49,160,180,0,156,1.0,-0.171961,True,False,False,...,True,False,False,True,False,True,False,False,True,False
2,37,130,283,0,98,0.0,0.770188,False,True,False,...,False,False,False,False,True,True,False,False,False,True
3,48,138,214,0,108,1.5,0.139040,True,False,True,...,False,False,False,True,False,False,True,False,True,False
4,54,150,195,0,122,0.0,-0.034755,False,True,False,...,True,False,False,True,False,True,False,False,False,True

In [26]:
y=df['HeartDisease']
y.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

In [28]:
x_train,x_test,y_train,y_test=train_test_split(
  x,y,test_size=0.2,random_state=42
)

In [29]:
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.fit_transform(x_test)

In [30]:
model=SVC(kernel='rbf')
model.fit(x_train,y_train)

SVC()

In [31]:
y_pred=model.predict(x_test)

In [33]:
model.score(x_test,y_test)

0.8833333333333333

In [38]:
from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier(n_estimators=100,oob_score=False)
model.fit(x_train,y_train)

RandomForestClassifier()

In [39]:
model.score(x_test,y_test)

0.8888888888888888