In [7]:
import pandas as pd
df=pd.read_csv("weather_data.csv",parse_dates=["day"])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [11]:
import pandas as pd
df=pd.read_csv("weather_data.csv",parse_dates=["day"])
df.set_index('day',inplace=True)
df_filled=df.fillna(0)
df_filled

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [14]:
import pandas as pd
df=pd.read_csv("weather_data.csv",parse_dates=["day"])
df.set_index('day',inplace=True)
df.fillna({
  'temperature':df.temperature.mean(),
  'windspeed':df.windspeed.mean(),
  'event':'No Event'
})

            temperature  windspeed     event
day
2017-01-01        32.00       6.00      Rain
2017-01-04        33.22       9.00     Sunny
2017-01-05        28.00       8.42      Snow
2017-01-06        33.22       7.00  No Event
2017-01-07        32.00       8.42      Rain
2017-01-08        33.22       8.42     Sunny
2017-01-09        33.22       8.42  No Event
2017-01-10        34.10       8.10    Cloudy
2017-01-11        40.00      12.00     Sunny

In [18]:
import pandas as pd
df=pd.read_csv("weather_data.csv",parse_dates=["day"])
df.set_index('day',inplace=True)
df=df.ffill(limit=1)#forward fill
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [19]:
import pandas as pd
df=pd.read_csv("weather_data.csv",parse_dates=["day"])
df.set_index('day',inplace=True)
df=df.bfill()#backward fill
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.1    Rain
2017-01-08         34.1        8.1   Sunny
2017-01-09         34.1        8.1  Cloudy
2017-01-10         34.1        8.1  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
import pandas as pd
df=pd.read_csv("weather_data.csv",parse_dates=["day"])
df.set_index('day',inplace=True)
df=df.ffill()#forward fill
df.interpolate()

TypeError: Cannot interpolate with str dtype