## <font color="maroon"><h4 align="center">Read/Write CSV and Excel Files (Exercise)</font>

In [13]:
import pandas as pd

### <font color="purple">**Question1**</font>
- Read the csv file with name "movies_data.csv"
- Show the Top5 rows

In [2]:
#read the csv file into the variable 'df'
import pandas as pd
df=pd.read_csv("movies_data.csv")
df.head(5)

#show the top 5 rows

,movie_id,title,industry,language,release_year,imdb_rating,studio,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,Kannada,2022,8.4,Hombale Films,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,English,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,English,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD
3,104,Thor: Ragnarok,Hollywood,English,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD
4,105,Thor: Love and Thunder,Hollywood,English,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD

### <font color="purple">**Question2**</font>
- Add a new column "year_classify" to the above dataframe.
- If release_year is less than 2000, then 'before 2000' or else 'From 2000'

In [8]:
#add the column "year_classify"
import pandas as pd
df=pd.read_csv("movies_data.csv")
df["year_classify"] = df["release_year"].apply(lambda x: 'before 2000' if x < 2000 else 'From 2000')
df.head(10)
#show the df

,movie_id,title,industry,language,release_year,imdb_rating,studio,budget,revenue,unit,currency,year_classify
0,101,K.G.F: Chapter 2,Bollywood,Kannada,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,From 2000
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,English,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,From 2000
2,103,Thor: The Dark World,Hollywood,English,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,From 2000
3,104,Thor: Ragnarok,Hollywood,English,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,From 2000
4,105,Thor: Love and Thunder,Hollywood,English,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,From 2000
5,111,The Shawshank Redemption,Hollywood,English,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,before 2000
6,113,Interstellar,Hollywood,English,2014,8.6,Warner Bros. Pictures,165.0,701.8,Millions,USD,From 2000
7,115,The Pursuit of Happyness,Hollywood,English,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,From 2000
8,116,Gladiator,Hollywood,English,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,From 2000
9,117,Titanic,Hollywood,English,1997,7.9,Paramount Pictures,200.0,2202.0,Millions,USD,before 2000

### <font color="purple">**Question3**</font>

- Save the above dataframe with the name "final_movie_data.csv" and include only columns 'movie_id', 'title', 'budget', 'revenue' and 'year_classify'. Also set index to False**.

In [10]:
#save the dataframe
#add the column "year_classify"
import pandas as pd
df=pd.read_csv("movies_data.csv")
df["year_classify"] = df["release_year"].apply(lambda x: 'before 2000' if x < 2000 else 'From 2000')
df=pd.DataFrame({'Name':['movie_id','title','budget','revenue','year_classify']})
df.to_csv('final_movie-data.csv',index=False)
#show the df