In [2]:
import pandas as pd
df=pd.read_csv("weather_by_cities.csv")
df.head(5)

        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
4  1/1/2017    mumbai           90          5  Sunny

In [9]:
import pandas as pd
india_weather=pd.DataFrame({
  'city':["mumbai","delhi","banglore"],
  'temperature':[32,45,30],
  'humidity':[80,60,78]
})

india_weather

us_weather=pd.DataFrame({
  'city':["new york","chicago","orlando"],
  'temperature':[21,13,35],
  'humidity':[68,65,75]
})

us_weather


df=pd.concat([india_weather,us_weather],keys=["india","usa"])

df.loc['usa']

       city  temperature  humidity
0  new york           21        68
1   chicago           13        65
2   orlando           35        75

In [10]:
import pandas as pd
india_weather=pd.DataFrame({
  'city':["mumbai","delhi","banglore"],
  'temperature':[32,45,30],
  'humidity':[80,60,78]
})

india_weather

us_weather=pd.DataFrame({
  'city':["new york","chicago","orlando"],
  'temperature':[21,13,35],
  'humidity':[68,65,75]
})

us_weather


temperature_df=pd.DataFrame({
  "city":["mumbai","delhi","banglore"],
  "temperature":[32,45,33]
})

temperature_df

       city  temperature
0    mumbai           32
1     delhi           45
2  banglore           33

In [14]:
import pandas as pd
df1=pd.DataFrame({
    'city':["new york","chicago","orlando"],
  'temperature':[21,13,35],
})


df2=pd.DataFrame({
  'city':["new york","chicago","orlando"],
  'humidity':[68,65,75]
})

df=pd.merge(df1,df2)
df

       city  temperature  humidity
0  new york           21        68
1   chicago           13        65
2   orlando           35        75

In [ ]:
import pandas as pd
df1=pd.DataFrame({
    'city':["new york","chicago","orlando","baltimore"],
  'temperature':[21,13,35,38],
})


df2=pd.DataFrame({
  'city':["chicago","new york","san diego"],
  'humidity':[68,65,75]
})

df=pd.merge(df1,df2,how="inner")
df

       city  temperature  humidity
0  new york           21        65
1   chicago           13        68